{
 "title": "Air quality",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Standard measurements",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pm_standard",
     "select": [
      [
       { "params": [ "pm1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 1.0" ], "type": "alias" }
      ],
      [
       { "params": [ "pm10" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 10" ], "type": "alias" }
      ],
      [
       { "params": [ "pm25" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 2.5" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Atmospheric measurements",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pm_atm",
     "select": [
      [
       { "params": [ "pm1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 1.0" ], "type": "alias" }
      ],
      [
       { "params": [ "pm10" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 10" ], "type": "alias" }
      ],
      [
       { "params": [ "pm25" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 2.5" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "p/dL" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pm",
     "select": [
      [
       { "params": [ "pm03" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 0.3" ], "type": "alias" }
      ],
      [
       { "params": [ "pm05" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 0.5" ], "type": "alias" }
      ],
      [
       { "params": [ "pm10" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 1.0" ], "type": "alias" }
      ],
      [
       { "params": [ "pm25" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 2.5" ], "type": "alias" }
      ],
      [
       { "params": [ "pm50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 5" ], "type": "alias" }
      ],
      [
       { "params": [ "pm100" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM 10" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}